export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CLEAR_ERROR = 'AUTH_CLEAR_ERROR';
export const AUTH_REDIRECT_PATH = 'AUTH_REDIRECT_PATH';

export const TODO_START = 'TODO_START';
export const TODO_FAIL = 'TODO_FAIL';
export const TODO_UPDATE_ITEM = 'TODO_UPDATE_ITEM';
export const TODO_UPDATE_LIST = 'TODO_UPDATE_LIST';
export const TODO_CLEAR_ERROR = 'TODO_CLEAR_ERROR';
